name = "Maimoon"
license = "MIT"
licenselink = "https://github.com/funkydan2/hugo-kiera/blob/master/LICENSE.md"
description = "Hugo Theme for creative and technical writing"
homepage = "https://github.com/maimoon08/Myfirstblog"
tags = ["blog","minimal","responsive"]
features = ["blog","disqus","google-analytics","font-awesome"]
min_version = "0.55.0"

[author]
  name = "Maimunat Kabir"
  homepage = "https://github.com/maimoon08/Myfirstblog"

[original]
  name = "maimoon08"
  homepage = "maimoon08/Myfirstblog"
  repo = "https://github.com/maimoon08/Myfirstblog"
